version: '3'
services:
  cloud-zipkin1:
    image: scia/cloud-zipkin:$zipkin_version
    container_name: cloud-zipkin1
    hostname: $zipkin_host_ip
    extra_hosts:
      - "config1:$config_host_ip"
      - "config2:$config_host_ip"
      - "eureka1:$eureka_host_ip"
      - "eureka2:$eureka_host_ip"
      - "eureka3:$eureka_host_ip"
      - "admin:$admin_host_ip"
    privileged: true
    ports:
      - "9411:9411"
    environment:
      ARGS: "\
      --ARGS_CONFIG_SERVICE_HOST1=config1 \
      --ARGS_CONFIG_SERVICE_PORT1=8888 \
      --ARGS_CONFIG_SERVICE_HOST2=config2 \
      --ARGS_CONFIG_SERVICE_PORT2=8889 \
      --ARGS_CONFIG_SECURITY_USERNAME=admin \
      --ARGS_CONFIG_SECURITY_PASSWORD=111 \
      --ARGS_ZIPKIN_SERVER_PORT=9411 \
      --ARGS_ADMIN_HOSTNAME=admin \
      --ARGS_ADMIN_PORT=8100 \
      --ARGS_EUREKA1_HOSTNAME=eureka1 --ARGS_EUREKA1_PORT=8761 \
      --ARGS_EUREKA2_HOSTNAME=eureka2 --ARGS_EUREKA2_PORT=8762 \
      --ARGS_EUREKA3_HOSTNAME=eureka3 --ARGS_EUREKA3_PORT=8763"