version: '3'
services:
  service-provider1:
    image: scia/service-provider:$provider_version
    container_name: service-provider1
    hostname: $provider_host_ip
    extra_hosts:
      - "config1:$config_host_ip"
      - "config2:$config_host_ip"
      - "eureka1:$eureka_host_ip"
      - "eureka2:$eureka_host_ip"
      - "eureka3:$eureka_host_ip"
      - "zipkin:$zipkin_host_ip"
    privileged: true
    ports:
      - "8081:8081"
    environment:
      ARGS: "\
      --ARGS_CONFIG_SERVICE_HOST1=config1 \
      --ARGS_CONFIG_SERVICE_PORT1=8888 \
      --ARGS_CONFIG_SERVICE_HOST2=config2 \
      --ARGS_CONFIG_SERVICE_PORT2=8889 \
      --ARGS_CONFIG_SECURITY_USERNAME=admin \
      --ARGS_CONFIG_SECURITY_PASSWORD=111 \
      --ARGS_PROVIDER_SERVER_PORT=8081 \
      --ARGS_ZIPKIN_HOSTNAME=zipkin \
      --ARGS_ZIPKIN_PORT=9411 \
      --ARGS_EUREKA1_HOSTNAME=eureka1 --ARGS_EUREKA1_PORT=8761 \
      --ARGS_EUREKA2_HOSTNAME=eureka2 --ARGS_EUREKA2_PORT=8762 \
      --ARGS_EUREKA3_HOSTNAME=eureka3 --ARGS_EUREKA3_PORT=8763"