server:
  port: ${ARGS_CONFIG_SERVICE_PORT}

spring:
  application:
    name: cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/BeanZero/SpringCloud-In-Action
          search-paths: cloud-config/src/main/resources/respo
#          username: ${ARGS_CONFIG_SERVICE_USERNAME}
#          password: ${ARGS_CONFIG_SERVICE_PASSWORD}
  security:
    user:
      name: ${ARGS_CONFIG_SECURITY_USERNAME}
      password: ${ARGS_CONFIG_SECURITY_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone:
          - http://${ARGS_EUREKA1_HOSTNAME}:${ARGS_EUREKA1_PORT}/eureka/
          - http://${ARGS_EUREKA2_HOSTNAME}:${ARGS_EUREKA2_PORT}/eureka/
          - http://${ARGS_EUREKA3_HOSTNAME}:${ARGS_EUREKA3_PORT}/eureka/

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health, info